
### local
GET http://localhost:7071/api/HttpTriggerCSharp?containerName=demo&accountName=demoacc


### deployed
### replace with correct storage account container name & acc name

GET https://begim1975-demostorsdkfunc.azurewebsites.net/api/HttpTriggerCSharp?containerName=demo&accName=begimreadfromdemo
